sudo: required
services:
  - docker

script:
  - docker build -t annydesigns/node .
  - docker images mannydesigns/node

before-deploy:
  - docker login -u "asthalearn" -p "Dock20199"

deploy:
  provider: script
  script: docker push mannydesigns/node
  on: 
    branch: master
